name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday.

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2', 'head']
    continue-on-error: ${{ matrix.ruby-version == 'head' }}

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake
